//! `proxxx init` — write a starter config.toml. First-mile UX: the
//! config-not-found error message points here, so this command MUST
//! work on a fresh machine without an existing config.

use anyhow::Result;

/// Template content written by `proxxx init`. Mirrors the shape of
/// `ProfileConfig` (one profile per file in MVP). Required fields
/// are uncommented with placeholder values; optional sections (HITL
/// via Telegram, SSH layer, alerts, policies, PBS) are commented out
/// so an operator who only wants the API client doesn't have to
/// delete chunks. Inline comments document every secret-resolution
/// path so an operator who doesn't want plain-text secrets can pick
/// env / file / keychain at a glance.
const INIT_CONFIG_TEMPLATE: &str = r#"# proxxx — generated by `proxxx init`
#
# Prefer `proxxx init --interactive` for an end-to-end wizard that
# probes the cluster live before write (URL reachability, auth, TLS,
# optional SSH key auto-discovery + per-guest overrides, optional
# Telegram). This template path exists for operators who want to
# hand-edit every field — fill in the values below, then run
# `proxxx ls nodes` to validate. See `proxxx --help` for the full
# subcommand list and `proxxx version --json` for build metadata.
#
# Secret resolution order (the same for every `*_secret` field):
#   1. CLI flag (`--token-secret`, `--pbs-token-secret`)
#   2. Env var (`PROXXX_TOKEN_SECRET`, `PROXXX_PBS_TOKEN_SECRET`)
#   3. `*_secret_file` path (must be 0600 on Unix or proxxx refuses)
#   4. OS keychain ("proxxx" / "token_secret" or "pbs_token_secret")
# Plain-text inline secrets are accepted but discouraged.

# ── Required: Proxmox VE REST connection ─────────────────────
url = "https://pve1.lan:8006"
user = "root@pam"
auth = "token"                   # "token" | "password"
verify_tls = true                # SET TO false ONLY for homelab clusters with self-
                                 # signed certs. Disabling TLS verification exposes the
                                 # full API + WebSocket traffic (incl. serial-console
                                 # tickets) to MITM. The flag is per-profile and also
                                 # propagates to the WebSocket termproxy client.
# tls_pin_mode = "tofu"          # Optional: opt-in TLS certificate pinning (Trust On
                                 # First Use). On first connect proxxx snapshots the
                                 # cluster's leaf cert under <config_dir>/known_certs/
                                 # and refuses subsequent connections that present a
                                 # different cert. Recommended for self-signed homelabs:
                                 # gives you MITM detection without a real CA chain.
                                 # Delete the pinned file to re-trust (e.g. after a legit
                                 # cert renewal).
rate_limit = 10                  # API calls per second (default 10)

# Token auth (recommended over password for headless tools).
# Build it with: pveum user token add root@pam proxxx --privsep=1
token_id = "proxxx"
# token_secret = "00000000-0000-0000-0000-000000000000"
# token_secret_file = "/etc/proxxx/pve.secret"   # 0600 perms required

# Or password auth — proxxx logs in via /access/ticket and refreshes
# the cookie automatically. Useful for ad-hoc sessions, not pipelines.
# auth = "password"
# password = "..."

# ── Optional: HITL approval gate via Telegram ────────────────
# When `--secure` is set OR a [[policies]] entry matches a destructive
# action, proxxx sends an approval request to Telegram and blocks the
# operation until Approve/Deny is clicked. Deny-on-timeout (120 s).
# [telegram]
# bot_token = "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
# chat_id = "-1001234567890"

# Per-action policies. `action` matches the dispatch identifier used
# internally (start, stop, restart, delete, migrate, exec, move_disk,
# resize_disk, …). `target` is "*" or "tag:<name>" or a vmid as string.
# [[policies]]
# action = "delete"
# target = "tag:prod"
# channel = "telegram"
# require = 1                    # Number of approvals needed

# ── Optional: SSH layer (SSH layer) ───────────────────────────
# Enables features that can't go through the Proxmox REST API:
#   - patch apply (apt-get on the node)
#   - `proxxx perms <user>` (pveum shell-out)
#   - per-guest SSH session (`proxxx ssh <vmid>`)
# [ssh]
# user = "root"
# key_path = "~/.ssh/id_ed25519"
# # known_hosts_path = "~/.ssh/known_hosts"  # default

# ── Optional: PBS (Proxmox Backup Server) connection ─────────
# Read-only browse via REST; restore shells out to proxmox-backup-client
# (Linux required for the restore subprocess).
# [pbs]
# url = "https://pbs.lan:8007"
# user = "root@pam"
# token_id = "proxxx"
# # token_secret = "..."
# fingerprint = "AB:CD:EF:..."   # PBS TLS fingerprint
# verify_tls = false

# ── Optional: alerts engine (rule-based notifier) ────────────
# Distinct from PVE 8+ native notifications — this is the proxxx-side
# rule engine for `proxxx alerts watch`. Channels: telegram, ntfy, webhook.
# [[alerts]]
# rule_id = "node-down"
# predicate = "node_offline"
# severity = "critical"
# route = "telegram:default"
"#;

/// `proxxx init` — create or extend config.toml.
///
/// * `profile_name == None` — write the flat starter template (first-run
///   UX). Refuses to clobber an existing config without `force`.
/// * `profile_name == Some(name)` — **append** a `[profiles.name]` block
///   to the existing config, preserving every other profile, comment, and
///   formatting (via `toml_edit`). Creates the file if absent. Refuses to
///   overwrite a profile of the same name without `force`. This is the
///   multi-cluster path: `proxxx init --profile prod` then
///   `proxxx init --profile lab`, etc.
///
/// Honors the `PROXXX_CONFIG` override via `config::resolved_config_path`.
pub fn execute(force: bool, profile_name: Option<&str>) -> Result<(serde_json::Value, i32)> {
    match profile_name {
        Some(name) => add_profile(name, force),
        None => write_flat_template(force),
    }
}

/// Resolve the config path + its parent dir, both honoring `PROXXX_CONFIG`.
fn config_paths() -> Result<(std::path::PathBuf, std::path::PathBuf)> {
    let config_path = crate::config::resolved_config_path();
    let config_dir = config_path
        .parent()
        .map(std::path::Path::to_path_buf)
        .ok_or_else(|| {
            anyhow::anyhow!("config path {} has no parent dir", config_path.display())
        })?;
    Ok((config_dir, config_path))
}

/// Atomic write: temp file in the same dir + fsync + rename. A partial
/// write can never leave a half-config the next `load_config` would
/// parse-error on. Sets 0600 on Unix (the file may hold inline secrets).
fn atomic_write(
    config_dir: &std::path::Path,
    config_path: &std::path::Path,
    body: &str,
) -> Result<()> {
    use anyhow::Context as _;
    use std::io::Write as _;

    std::fs::create_dir_all(config_dir).with_context(|| {
        format!(
            "creating config directory {} (check filesystem perms)",
            config_dir.display()
        )
    })?;
    let tmp_path = config_dir.join("config.toml.proxxx-init-tmp");
    {
        let mut f = std::fs::File::create(&tmp_path).with_context(|| {
            format!(
                "creating temp config at {} (check perms)",
                tmp_path.display()
            )
        })?;
        f.write_all(body.as_bytes())?;
        f.sync_all()?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(&tmp_path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("setting 0600 on {}", tmp_path.display()))?;
    }
    std::fs::rename(&tmp_path, config_path).with_context(|| {
        format!(
            "renaming temp config into place at {}",
            config_path.display()
        )
    })?;
    Ok(())
}

fn write_flat_template(force: bool) -> Result<(serde_json::Value, i32)> {
    let (config_dir, config_path) = config_paths()?;
    if config_path.exists() && !force {
        anyhow::bail!(
            "Config already exists at {}. Re-run with --force to overwrite, or add a \
             named profile with `proxxx init --profile <name>` (appends, never clobbers).",
            config_path.display()
        );
    }
    atomic_write(&config_dir, &config_path, INIT_CONFIG_TEMPLATE)?;
    Ok((
        serde_json::json!({
            "wrote": config_path.display().to_string(),
            "force": force,
            "next_step": "edit `url`, `user`, `token_id`, `token_secret`, then run `proxxx ls nodes`",
        }),
        0,
    ))
}

/// Append a `[profiles.<name>]` block to the existing config (or a fresh
/// one), preserving everything else. Format-preserving via `toml_edit`.
fn add_profile(name: &str, force: bool) -> Result<(serde_json::Value, i32)> {
    use anyhow::Context as _;
    use toml_edit::{value, Item, Table};

    if name.trim().is_empty() {
        anyhow::bail!("profile name must not be empty");
    }

    let (config_dir, config_path) = config_paths()?;

    let mut doc = if config_path.exists() {
        let content = std::fs::read_to_string(&config_path)
            .with_context(|| format!("reading existing config at {}", config_path.display()))?;
        content.parse::<toml_edit::DocumentMut>().with_context(|| {
            format!(
                "parsing existing config at {} as TOML",
                config_path.display()
            )
        })?
    } else {
        let mut d = toml_edit::DocumentMut::new();
        // Friendly header so a profile-only config isn't a bare table dump.
        d.decor_mut().set_prefix(
            "# proxxx config — created by `proxxx init --profile`.\n\
             # Each [profiles.NAME] is one Proxmox endpoint. Use\n\
             # `proxxx --profile <name> ...`, or `proxxx fleet` to view all\n\
             # of them read-only. Optionally set `default = \"<name>\"` below.\n\n",
        );
        d
    };

    // Ensure a [profiles] table exists (non-implicit so it can hold subtables).
    if doc.get("profiles").is_none() {
        let mut t = Table::new();
        t.set_implicit(true); // render only the [profiles.<name>] header, not a bare [profiles]
        doc["profiles"] = Item::Table(t);
    }
    let profiles = doc["profiles"]
        .as_table_mut()
        .ok_or_else(|| anyhow::anyhow!("`profiles` in config.toml is not a table"))?;

    let existed = profiles.contains_key(name);
    if existed && !force {
        anyhow::bail!(
            "Profile '{}' already exists in {}. Re-run with --force to overwrite just that \
             profile (other profiles are preserved either way).",
            name,
            config_path.display()
        );
    }

    let mut t = Table::new();
    t.insert("url", value("https://pve1.lan:8006"));
    t.insert("user", value("root@pam"));
    t.insert("auth", value("token"));
    t.insert("token_id", value("proxxx"));
    // token_secret resolves via env / *_secret_file / keychain — leave the
    // inline value out so the placeholder profile doesn't ship a fake one.
    t.insert("verify_tls", value(true));
    t.insert("rate_limit", value(10_i64));
    // read-only lock is off by default; hint at it for prod profiles.
    let mut ro = toml_edit::Formatted::new(false);
    *ro.decor_mut().suffix_mut() =
        "  # set true (+ a PVEAuditor token) to refuse all writes on this profile".into();
    t.insert("read_only", Item::Value(toml_edit::Value::Boolean(ro)));
    profiles.insert(name, Item::Table(t));

    atomic_write(&config_dir, &config_path, &doc.to_string())?;

    Ok((
        serde_json::json!({
            "wrote": config_path.display().to_string(),
            "profile": name,
            "action": if existed { "updated" } else { "added" },
            "force": force,
            "next_step": format!(
                "edit [profiles.{name}] url/user/token_id, set the secret \
                 (token_secret_file / PROXXX_TOKEN_SECRET / keychain), then run \
                 `proxxx --profile {name} ls nodes`"
            ),
        }),
        0,
    ))
}
