//! `proxxx init` — write a starter config.toml. First-mile UX: the
//! config-not-found error message points here, so this command MUST
//! work on a fresh machine without an existing config.

use anyhow::Result;

/// Template content written by `proxxx init`. Mirrors the shape of
/// `ProfileConfig` (one profile per file in MVP). Required fields
/// are uncommented with placeholder values; optional sections (HITL
/// via Telegram, SSH layer, alerts, policies, PBS) are commented out
/// so an operator who only wants the API client doesn't have to
/// delete chunks. Inline comments document every secret-resolution
/// path so an operator who doesn't want plain-text secrets can pick
/// env / file / keychain at a glance.
const INIT_CONFIG_TEMPLATE: &str = r#"# proxxx — generated by `proxxx init`
#
# Prefer `proxxx init --interactive` for an end-to-end wizard that
# probes the cluster live before write (URL reachability, auth, TLS,
# optional SSH key auto-discovery + per-guest overrides, optional
# Telegram). This template path exists for operators who want to
# hand-edit every field — fill in the values below, then run
# `proxxx ls nodes` to validate. See `proxxx --help` for the full
# subcommand list and `proxxx version --json` for build metadata.
#
# Secret resolution order (the same for every `*_secret` field):
#   1. CLI flag (`--token-secret`, `--pbs-token-secret`)
#   2. Env var (`PROXXX_TOKEN_SECRET`, `PROXXX_PBS_TOKEN_SECRET`)
#   3. `*_secret_file` path (must be 0600 on Unix or proxxx refuses)
#   4. OS keychain ("proxxx" / "token_secret" or "pbs_token_secret")
# Plain-text inline secrets are accepted but discouraged.

# ── Required: Proxmox VE REST connection ─────────────────────
url = "https://pve1.lan:8006"
user = "root@pam"
auth = "token"                   # "token" | "password"
verify_tls = true                # SET TO false ONLY for homelab clusters with self-
                                 # signed certs. Disabling TLS verification exposes the
                                 # full API + WebSocket traffic (incl. serial-console
                                 # tickets) to MITM. The flag is per-profile and also
                                 # propagates to the WebSocket termproxy client.
# tls_pin_mode = "tofu"          # Optional: opt-in TLS certificate pinning (Trust On
                                 # First Use). On first connect proxxx snapshots the
                                 # cluster's leaf cert under <config_dir>/known_certs/
                                 # and refuses subsequent connections that present a
                                 # different cert. Recommended for self-signed homelabs:
                                 # gives you MITM detection without a real CA chain.
                                 # Delete the pinned file to re-trust (e.g. after a legit
                                 # cert renewal).
rate_limit = 10                  # API calls per second (default 10)

# Token auth (recommended over password for headless tools).
# Build it with: pveum user token add root@pam proxxx --privsep=1
token_id = "proxxx"
# token_secret = "00000000-0000-0000-0000-000000000000"
# token_secret_file = "/etc/proxxx/pve.secret"   # 0600 perms required

# Or password auth — proxxx logs in via /access/ticket and refreshes
# the cookie automatically. Useful for ad-hoc sessions, not pipelines.
# auth = "password"
# password = "..."

# ── Optional: HITL approval gate via Telegram ────────────────
# When `--secure` is set OR a [[policies]] entry matches a destructive
# action, proxxx sends an approval request to Telegram and blocks the
# operation until Approve/Deny is clicked. Deny-on-timeout (120 s).
# [telegram]
# bot_token = "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
# chat_id = "-1001234567890"

# Per-action policies. `action` matches the dispatch identifier used
# internally (start, stop, restart, delete, migrate, exec, move_disk,
# resize_disk, …). `target` is "*" or "tag:<name>" or a vmid as string.
# [[policies]]
# action = "delete"
# target = "tag:prod"
# channel = "telegram"
# require = 1                    # Number of approvals needed

# ── Optional: SSH layer (SSH layer) ───────────────────────────
# Enables features that can't go through the Proxmox REST API:
#   - patch apply (apt-get on the node)
#   - `proxxx perms <user>` (pveum shell-out)
#   - per-guest SSH session (`proxxx ssh <vmid>`)
# [ssh]
# user = "root"
# key_path = "~/.ssh/id_ed25519"
# # known_hosts_path = "~/.ssh/known_hosts"  # default

# ── Optional: PBS (Proxmox Backup Server) connection ─────────
# Read-only browse via REST; restore shells out to proxmox-backup-client
# (Linux required for the restore subprocess).
# [pbs]
# url = "https://pbs.lan:8007"
# user = "root@pam"
# token_id = "proxxx"
# # token_secret = "..."
# fingerprint = "AB:CD:EF:..."   # PBS TLS fingerprint
# verify_tls = false

# ── Optional: alerts engine (rule-based notifier) ────────────
# Distinct from PVE 8+ native notifications — this is the proxxx-side
# rule engine for `proxxx alerts watch`. Channels: telegram, ntfy, webhook.
# [[alerts]]
# rule_id = "node-down"
# predicate = "node_offline"
# severity = "critical"
# route = "telegram:default"
"#;

/// `proxxx init` — write a starter config.toml to the OS-default
/// proxxx config directory. First-mile UX: the config-not-found
/// error message points here, so this command MUST work on a fresh
/// machine without an existing config.
pub fn execute(force: bool) -> Result<(serde_json::Value, i32)> {
    use anyhow::Context as _;
    use std::io::Write as _;

    let config_dir = directories::ProjectDirs::from("dev", "proxxx", "proxxx")
        .map(|d| d.config_dir().to_path_buf())
        .ok_or_else(|| anyhow::anyhow!("could not resolve OS config directory for proxxx"))?;

    let config_path = config_dir.join("config.toml");

    if config_path.exists() && !force {
        anyhow::bail!(
            "Config already exists at {}. Re-run with --force to overwrite.",
            config_path.display()
        );
    }

    std::fs::create_dir_all(&config_dir).with_context(|| {
        format!(
            "creating config directory {} (check filesystem perms)",
            config_dir.display()
        )
    })?;

    // Write atomically via a temp file in the same dir + rename — so a
    // partial write can't leave a half-template config.toml that the
    // next `load_config` call would parse-error on.
    let tmp_path = config_dir.join("config.toml.proxxx-init-tmp");
    {
        let mut f = std::fs::File::create(&tmp_path).with_context(|| {
            format!(
                "creating temp config at {} (check perms)",
                tmp_path.display()
            )
        })?;
        f.write_all(INIT_CONFIG_TEMPLATE.as_bytes())?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp_path, &config_path).with_context(|| {
        format!(
            "renaming temp config into place at {}",
            config_path.display()
        )
    })?;

    Ok((
        serde_json::json!({
            "wrote": config_path.display().to_string(),
            "force": force,
            "next_step": "edit `url`, `user`, `token_id`, `token_secret`, then run `proxxx ls nodes`",
        }),
        0,
    ))
}
