//! Storage surface: content upload/delete on a node's storage, cluster-wide
//! storage definitions CRUD, ISO/template library, recurring backup jobs,
//! Proxmox Backup Server browse + restore, LXC template catalog, ACME config.

use anyhow::Result;
use clap::Subcommand;
use serde_json::Value;
use std::sync::Arc;

use crate::cli::common::wait_and_classify;

#[derive(Debug, Subcommand)]
pub enum StorageCommand {
    /// Upload a local file (ISO, CT template, disk image for import)
    /// to a storage. Destination filename defaults to local basename.
    Upload {
        /// Node hosting the storage (must be reachable).
        node: String,
        /// Storage id (e.g. `local`, `storage`, `nfs-shared`).
        storage: String,
        /// Local file path to upload.
        local_path: std::path::PathBuf,
        /// PVE content bucket: `iso` | `vztmpl` | `import`.
        #[arg(long, default_value = "iso")]
        content: String,
        /// Override destination filename (default: local basename).
        #[arg(long = "as")]
        remote_filename: Option<String>,
        /// Block until the upload task completes.
        #[arg(long)]
        wait: bool,
    },
    /// Delete a content item by `volid`. Format:
    /// `<storage>:<type>/<file>` for files (e.g.
    /// `local:iso/ubuntu.iso`) or `<storage>:<vmid>/<disk>` for VM
    /// disks. Required: `--yes`.
    Delete {
        /// Node hosting the storage.
        node: String,
        /// Volid to delete (e.g. `local:iso/ubuntu-24.04.iso`).
        volid: String,
        /// Required: confirms this destructive op.
        #[arg(long)]
        yes: bool,
        /// Block until the delete task completes.
        #[arg(long)]
        wait: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum BackupJobsCommand {
    /// List every scheduled backup job cluster-wide.
    List,
    /// Show one job by id (the autogenerated `backup-…` string from
    /// list output). Returns the same shape as one row of `list`.
    Show { id: String },
    /// Create a new scheduled job. PVE auto-assigns the id; minimum
    /// required is `--schedule` + `--storage` + (`--all` OR `--vmid`).
    /// Use the web UI or `--raw KEY=VAL` for less-common knobs.
    Create {
        /// systemd-time format, e.g. `"mon..fri 02:00"`.
        #[arg(long)]
        schedule: String,
        /// Target storage id.
        #[arg(long)]
        storage: String,
        /// Backup ALL guests (mutually exclusive with --vmid).
        #[arg(long, default_value_t = false)]
        all: bool,
        /// CSV of VMIDs to back up (mutually exclusive with --all).
        #[arg(long)]
        vmid: Option<String>,
        /// `snapshot` (default) | `stop` | `suspend`.
        #[arg(long, default_value = "snapshot")]
        mode: String,
        /// `none` | `lzo` | `gzip` | `zstd`. PVE 7+ default is zstd.
        #[arg(long)]
        compress: Option<String>,
        /// Email destination for run notifications.
        #[arg(long)]
        mailto: Option<String>,
        /// `always` | `failure` (default).
        #[arg(long)]
        mailnotification: Option<String>,
        /// Retention DSL — e.g. `keep-last=3,keep-daily=7`.
        #[arg(long)]
        prune_backups: Option<String>,
        /// Free-form comment shown in the web UI.
        #[arg(long)]
        comment: Option<String>,
        /// Restrict to one node (default: cluster-wide).
        #[arg(long)]
        node: Option<String>,
        /// Raw param escape hatch — repeatable `KEY=VAL`, forwarded
        /// to PVE verbatim. Example: `--raw exclude-path=/tmp/.*`.
        #[arg(long)]
        raw: Vec<String>,
    },
    /// Update one or more fields on an existing job.
    Update {
        id: String,
        #[arg(long)]
        schedule: Option<String>,
        #[arg(long)]
        enabled: Option<bool>,
        #[arg(long)]
        compress: Option<String>,
        #[arg(long)]
        prune_backups: Option<String>,
        #[arg(long)]
        comment: Option<String>,
        /// Same escape hatch as `create --raw`.
        #[arg(long)]
        raw: Vec<String>,
    },
    /// Delete a scheduled job. Does NOT delete already-taken backup
    /// archives — only the future-runs schedule.
    Delete {
        id: String,
        /// Required for non-interactive confirmation.
        #[arg(long)]
        yes: bool,
    },
    /// Cluster-wide backup volume runtime info. PVE quirk: only the
    /// LITERAL `root@pam` user can call this — token auth gets 403
    /// regardless of ACL ("user != root@pam" in the source).
    Info,
    /// Extract one guest's config from a backup archive — peek at
    /// what the VM looked like when the backup was taken, without
    /// restoring. Returns plain text.
    ExtractConfig {
        #[arg(long)]
        node: String,
        /// Volume id, e.g.
        /// `local:backup/vzdump-qemu-100-2026_05_03-12_00_00.vma.zst`.
        #[arg(long)]
        volume: String,
    },
}

#[derive(Debug, Subcommand)]
pub enum StorageDefsCommand {
    List,
    Show {
        storage: String,
    },
    /// Create a new storage. PVE validates type-specific required fields
    /// inline (e.g. `nfs` requires `--server` + `--export`; `pbs`
    /// requires `--server` + `--datastore`).
    Create {
        /// Storage id (operator-chosen name).
        #[arg(long)]
        storage: String,
        /// Storage type: `dir` | `lvm` | `lvmthin` | `zfspool` | `nfs`
        /// | `cifs` | `iscsi` | `glusterfs` | `cephfs` | `rbd` | `pbs`
        /// | `btrfs` | `esxi`.
        #[arg(long, value_name = "TYPE")]
        storage_type: String,
        /// CSV: `vztmpl,iso,backup,images,rootdir,snippets`.
        #[arg(long)]
        content: Option<String>,
        /// CSV node-restriction. Empty = all nodes (default).
        #[arg(long)]
        nodes: Option<String>,
        /// 1 = visible to every node (NFS, PBS, `CephFS`, etc.).
        #[arg(long)]
        shared: Option<bool>,
        /// `dir` / `btrfs`: filesystem path.
        #[arg(long)]
        path: Option<String>,
        /// `nfs` / `cifs` / `pbs` / `iscsi`: server hostname/IP.
        #[arg(long)]
        server: Option<String>,
        /// `nfs`: export path on the server.
        #[arg(long)]
        export: Option<String>,
        /// `pbs`: datastore name.
        #[arg(long)]
        datastore: Option<String>,
        /// `pbs` / `cifs`: TLS fingerprint for verification.
        #[arg(long)]
        fingerprint: Option<String>,
        /// `cifs` / `pbs`: auth username.
        #[arg(long)]
        username: Option<String>,
        /// `zfspool` / `rbd`: ZFS dataset / Ceph pool name.
        #[arg(long)]
        pool: Option<String>,
        /// `lvm` / `lvmthin`: volume group name.
        #[arg(long)]
        vgname: Option<String>,
        /// `lvmthin`: thin pool name within `vgname`.
        #[arg(long)]
        thinpool: Option<String>,
        #[arg(long)]
        raw: Vec<String>,
    },
    /// Update an existing storage. `type` cannot be changed (PVE rejects
    /// with 400). Refuses no-op calls.
    Update {
        storage: String,
        #[arg(long)]
        content: Option<String>,
        #[arg(long)]
        nodes: Option<String>,
        #[arg(long)]
        disable: Option<bool>,
        #[arg(long)]
        shared: Option<bool>,
        /// `pbs` / `cifs`: TLS fingerprint.
        #[arg(long)]
        fingerprint: Option<String>,
        /// Comma-separated list of fields to clear (PVE PUT param `delete`).
        #[arg(long)]
        delete: Option<String>,
        #[arg(long)]
        raw: Vec<String>,
    },
    Delete {
        storage: String,
        #[arg(long)]
        yes: bool,
    },
}

/// ACME cluster-wide config. Five sub-trees mapping 1:1 to PVE
/// resources: `account` (CA registration), `plugin` (DNS-01/HTTP-01
/// challenge runners), `tos` / `directories` / `challenge-schema`
/// (read-only support endpoints).
#[derive(Debug, Subcommand)]
pub enum AcmeCommand {
    #[command(subcommand)]
    Account(AcmeAccountCommand),
    #[command(subcommand)]
    Plugin(AcmePluginCommand),
    /// Fetch the Terms-of-Service URL for the chosen ACME directory
    /// (defaults to PVE's default — usually Let's Encrypt prod).
    Tos {
        #[arg(long)]
        directory: Option<String>,
    },
    /// List ACME-compatible CAs PVE knows about.
    Directories,
    /// Dump the DNS-01 plugin schema list (raw JSON — wizard fodder).
    ChallengeSchema,
}

#[derive(Debug, Subcommand)]
pub enum AcmeAccountCommand {
    List,
    Show {
        name: String,
    },
    /// Register a new account with the ACME CA. Returns a UPID — the
    /// call is async (CA round-trip).
    Create {
        #[arg(long)]
        name: String,
        /// Contact email(s), CSV (`mailto:` prefix optional).
        #[arg(long)]
        contact: String,
        /// `ToS` URL to confirm acceptance — get it via `proxxx acme tos`.
        #[arg(long)]
        tos_url: Option<String>,
        /// ACME directory URL (defaults to LE prod).
        #[arg(long)]
        directory: Option<String>,
        /// External Account Binding key id (some CAs require it).
        #[arg(long)]
        eab_kid: Option<String>,
        #[arg(long)]
        eab_hmac_key: Option<String>,
        #[arg(long)]
        raw: Vec<String>,
    },
    /// Update account contact / state. Returns a UPID.
    Update {
        name: String,
        #[arg(long)]
        contact: Option<String>,
        #[arg(long)]
        raw: Vec<String>,
    },
    /// Deactivate the account on the CA + remove local config.
    /// Returns a UPID.
    Delete {
        name: String,
        #[arg(long)]
        yes: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum AcmePluginCommand {
    List,
    Show {
        plugin_id: String,
    },
    /// Create a challenge plugin. DNS-01 needs `--api` + `--data`;
    /// HTTP-01 (`--plugin-type standalone`) is config-free.
    Create {
        #[arg(long)]
        plugin_id: String,
        /// `dns` | `standalone` (HTTP-01).
        #[arg(long)]
        plugin_type: String,
        /// DNS plugin name (`cloudflare`, `route53`, `gandi_livedns`, ...).
        #[arg(long)]
        api: Option<String>,
        /// DNS API credentials (sub-spec, e.g. `CF_Token=…`).
        #[arg(long)]
        data: Option<String>,
        /// Seconds to wait for DNS propagation before validating.
        #[arg(long)]
        validation_delay: Option<u32>,
        #[arg(long)]
        raw: Vec<String>,
    },
    Update {
        plugin_id: String,
        #[arg(long)]
        api: Option<String>,
        #[arg(long)]
        data: Option<String>,
        #[arg(long)]
        validation_delay: Option<u32>,
        #[arg(long)]
        disable: Option<bool>,
        #[arg(long)]
        raw: Vec<String>,
    },
    Delete {
        plugin_id: String,
        #[arg(long)]
        yes: bool,
    },
}

/// LXC template catalog (PVE's curated upstream).
#[derive(Debug, Subcommand)]
pub enum AplinfoCommand {
    /// List available templates from the PVE catalog (≈ `pveam available`).
    List {
        /// Node from which to query the catalog (any cluster member works).
        #[arg(long)]
        node: String,
    },
    /// Download a template to a node's storage. Returns a UPID — long
    /// task (template fetch from PVE mirrors).
    Download {
        #[arg(long)]
        node: String,
        /// Target storage id (must support content type `vztmpl`).
        #[arg(long)]
        storage: String,
        /// Template name from `list` (e.g.
        /// `debian-12-standard_12.7-1_amd64.tar.zst`).
        #[arg(long)]
        template: String,
    },
}

#[derive(Debug, Subcommand)]
pub enum PbsCommand {
    /// Verify PBS connectivity and authentication. Prints PBS version on success.
    Ping,
    /// List datastores on the configured PBS server.
    Datastores,
    /// List snapshots in a datastore. Optional filters by guest type/id.
    Snapshots {
        #[arg(long)]
        store: String,
        /// Filter: backup type (`vm`, `ct`, `host`).
        #[arg(long)]
        backup_type: Option<String>,
        /// Filter: backup id (e.g. `100`).
        #[arg(long)]
        backup_id: Option<String>,
    },
    /// List archive files inside a specific snapshot.
    Files {
        #[arg(long)]
        store: String,
        #[arg(long = "type")]
        backup_type: String,
        #[arg(long)]
        backup_id: String,
        /// Snapshot timestamp (Unix seconds).
        #[arg(long = "time")]
        backup_time: u64,
    },
    /// Restore a full archive to a local target directory.
    /// Single-file extraction is NOT supported in this MVP — declared cut.
    Restore {
        #[arg(long)]
        store: String,
        /// Snapshot reference, e.g. `vm/100/2024-01-15T10:00:00Z`.
        #[arg(long)]
        snapshot: String,
        /// Archive name, e.g. `root.pxar.didx`.
        #[arg(long)]
        archive: String,
        /// Local directory to restore into.
        #[arg(long)]
        target: std::path::PathBuf,
        /// Required: confirms this writes to the local filesystem.
        #[arg(long)]
        yes: bool,
    },
}

#[derive(Debug, Subcommand)]
pub enum IsoCommand {
    /// List the curated library entries (id, distro, version, sha256).
    List,
    /// Download a curated entry by id, or a custom URL.
    Download {
        /// Library entry id (see `iso list`). Mutually exclusive with `--url`.
        #[arg(long)]
        id: Option<String>,
        /// Custom URL (overrides `--id`). Pair with `--filename`.
        #[arg(long)]
        url: Option<String>,
        /// Filename to store as. Required with `--url`.
        #[arg(long)]
        filename: Option<String>,
        /// Optional SHA-256 to pin (Proxmox verifies).
        #[arg(long)]
        sha256: Option<String>,
        /// Content category: iso | import | vztmpl. Required with `--url`.
        #[arg(long)]
        content: Option<String>,
        /// Target node (which Proxmox node performs the download).
        #[arg(long)]
        node: String,
        /// Target storage name on that node.
        #[arg(long)]
        storage: String,
    },
}

pub async fn execute_storage(
    client: &Arc<crate::api::PxClient>,
    action: StorageCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;
    match action {
        StorageCommand::Upload {
            node,
            storage,
            local_path,
            content,
            remote_filename,
            wait,
        } => {
            // Validate content bucket at the CLI boundary so the user
            // gets a clear error rather than PVE's generic schema 400.
            let valid = ["iso", "vztmpl", "import"];
            if !valid.contains(&content.as_str()) {
                anyhow::bail!(
                    "invalid content type '{content}'; valid: {}",
                    valid.join(", ")
                );
            }
            let upid = client
                .upload_to_storage(
                    &node,
                    &storage,
                    &local_path,
                    &content,
                    remote_filename.as_deref(),
                )
                .await?;
            let envelope = serde_json::json!({
                "node": node,
                "storage": storage,
                "filename": remote_filename
                    .clone()
                    .or_else(|| {
                        local_path.file_name()
                            .and_then(|s| s.to_str())
                            .map(std::string::ToString::to_string)
                    }),
                "content": content,
                "task": upid,
            });
            if wait {
                let (status_json, exit) = wait_and_classify(client, &node, &upid).await?;
                Ok((
                    serde_json::json!({
                        "request": envelope,
                        "task_status": status_json,
                    }),
                    exit,
                ))
            } else {
                Ok((envelope, 0))
            }
        }
        StorageCommand::Delete {
            node,
            volid,
            yes,
            wait,
        } => {
            if !yes {
                anyhow::bail!("storage delete is destructive — re-run with --yes");
            }
            // Volid form: `<storage>:<type>/<file>`. Extract the
            // storage portion to feed into the URL path. PVE wants
            // BOTH the storage name in the URL AND the full volid
            // (which redundantly includes the storage prefix).
            let storage = volid
                .split_once(':')
                .ok_or_else(|| {
                    anyhow::anyhow!("invalid volid '{volid}': expected '<storage>:<type>/<file>'")
                })?
                .0;
            let task = client
                .delete_storage_content(&node, storage, &volid)
                .await?;
            let envelope = serde_json::json!({
                "node": node,
                "storage": storage,
                "volid": volid,
                "task": task,
            });
            // Some storage backends return None (instant delete).
            // For those, --wait is a no-op (nothing to poll).
            if let (true, Some(upid)) = (wait, task.as_deref()) {
                let (status_json, exit) = wait_and_classify(client, &node, upid).await?;
                Ok((
                    serde_json::json!({
                        "request": envelope,
                        "task_status": status_json,
                    }),
                    exit,
                ))
            } else {
                Ok((envelope, 0))
            }
        }
    }
}

/// Backup-jobs CRUD CLI. proxxx already has `proxxx backup` for
/// one-shot vzdump; this surface manages the RECURRING jobs PVE
/// stores cluster-wide at `/cluster/backup`.
pub async fn execute_backup_jobs(
    client: &Arc<crate::api::PxClient>,
    action: BackupJobsCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;

    // Helper: fold typed flags + raw `KEY=VAL` overrides into the
    // flat (str, str) param list PVE expects. Raw entries win on
    // conflict — explicit operator override of a typed default.
    fn build_params<'a>(
        typed: Vec<(&'a str, String)>,
        raw: &'a [String],
    ) -> Result<Vec<(&'a str, String)>> {
        let mut out = typed;
        for spec in raw {
            let (k, v) = spec
                .split_once('=')
                .ok_or_else(|| anyhow::anyhow!("--raw expects KEY=VAL, got {spec:?}"))?;
            // Drop any typed entry under the same key.
            out.retain(|(ek, _)| *ek != k);
            // Lifetime hack: leak the key so it's 'static — fine for
            // CLI lifetime, this fn returns immediately into a one-
            // shot dispatch. Avoids threading another lifetime through
            // the entire CRUD signature.
            let key_static: &'static str = Box::leak(k.to_string().into_boxed_str());
            out.push((key_static, v.to_string()));
        }
        Ok(out)
    }

    match action {
        BackupJobsCommand::List => {
            let jobs = client.list_backup_jobs().await?;
            Ok((serde_json::to_value(jobs)?, 0))
        }
        BackupJobsCommand::Show { id } => {
            let job = client.get_backup_job(&id).await?;
            Ok((serde_json::to_value(job)?, 0))
        }
        BackupJobsCommand::Create {
            schedule,
            storage,
            all,
            vmid,
            mode,
            compress,
            mailto,
            mailnotification,
            prune_backups,
            comment,
            node,
            raw,
        } => {
            if all && vmid.is_some() {
                anyhow::bail!("--all and --vmid are mutually exclusive");
            }
            if !all && vmid.is_none() {
                anyhow::bail!("either --all or --vmid is required");
            }
            let mut typed: Vec<(&str, String)> =
                vec![("schedule", schedule), ("storage", storage), ("mode", mode)];
            if all {
                typed.push(("all", "1".to_string()));
            }
            if let Some(v) = vmid {
                typed.push(("vmid", v));
            }
            if let Some(c) = compress {
                typed.push(("compress", c));
            }
            if let Some(m) = mailto {
                typed.push(("mailto", m));
            }
            if let Some(mn) = mailnotification {
                typed.push(("mailnotification", mn));
            }
            if let Some(pb) = prune_backups {
                typed.push(("prune-backups", pb));
            }
            if let Some(c) = comment {
                typed.push(("comment", c));
            }
            if let Some(n) = node {
                typed.push(("node", n));
            }
            let merged = build_params(typed, &raw)?;
            let pairs: Vec<(&str, &str)> = merged.iter().map(|(k, v)| (*k, v.as_str())).collect();
            client.create_backup_job(&pairs).await?;
            Ok((serde_json::json!({"status": "created"}), 0))
        }
        BackupJobsCommand::Update {
            id,
            schedule,
            enabled,
            compress,
            prune_backups,
            comment,
            raw,
        } => {
            let mut typed: Vec<(&str, String)> = Vec::new();
            if let Some(s) = schedule {
                typed.push(("schedule", s));
            }
            if let Some(e) = enabled {
                typed.push(("enabled", if e { "1".into() } else { "0".into() }));
            }
            if let Some(c) = compress {
                typed.push(("compress", c));
            }
            if let Some(pb) = prune_backups {
                typed.push(("prune-backups", pb));
            }
            if let Some(c) = comment {
                typed.push(("comment", c));
            }
            let merged = build_params(typed, &raw)?;
            if merged.is_empty() {
                anyhow::bail!(
                    "update needs at least one --field or --raw KEY=VAL — \
                     no-op refused (would silently succeed)"
                );
            }
            let pairs: Vec<(&str, &str)> = merged.iter().map(|(k, v)| (*k, v.as_str())).collect();
            client.update_backup_job(&id, &pairs).await?;
            Ok((serde_json::json!({"status": "updated", "id": id}), 0))
        }
        BackupJobsCommand::Delete { id, yes } => {
            if !yes {
                anyhow::bail!(
                    "`backup-jobs delete {id}` is destructive — re-run with --yes to confirm"
                );
            }
            client.delete_backup_job(&id).await?;
            Ok((serde_json::json!({"status": "deleted", "id": id}), 0))
        }
        BackupJobsCommand::Info => {
            // Will return ApiError::Forbidden under token auth — let
            // the typed error bubble up through the standard CLI exit
            // mapping (Phase 7's write-path completion).
            let info = client.cluster_backup_info().await?;
            Ok((info, 0))
        }
        BackupJobsCommand::ExtractConfig { node, volume } => {
            let cfg = client.extract_backup_config(&node, &volume).await?;
            Ok((
                serde_json::json!({"node": node, "volume": volume, "config": cfg}),
                0,
            ))
        }
    }
}

/// Cluster-wide storage definitions dispatch.
#[allow(clippy::too_many_lines)]
pub async fn execute_storage_defs(
    client: &Arc<crate::api::PxClient>,
    action: StorageDefsCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;

    fn build_params<'a>(
        typed: Vec<(&'a str, String)>,
        raw: &'a [String],
    ) -> Result<Vec<(&'a str, String)>> {
        let mut out = typed;
        for spec in raw {
            let (k, v) = spec
                .split_once('=')
                .ok_or_else(|| anyhow::anyhow!("--raw expects KEY=VAL, got {spec:?}"))?;
            out.retain(|(ek, _)| *ek != k);
            let key_static: &'static str = Box::leak(k.to_string().into_boxed_str());
            out.push((key_static, v.to_string()));
        }
        Ok(out)
    }
    fn as_refs<'a>(v: &'a [(&'a str, String)]) -> Vec<(&'a str, &'a str)> {
        v.iter().map(|(k, s)| (*k, s.as_str())).collect()
    }

    match action {
        StorageDefsCommand::List => {
            let storages = client.list_cluster_storages().await?;
            Ok((serde_json::to_value(storages)?, 0))
        }
        StorageDefsCommand::Show { storage } => {
            let s = client.get_cluster_storage(&storage).await?;
            Ok((serde_json::to_value(s)?, 0))
        }
        StorageDefsCommand::Create {
            storage,
            storage_type,
            content,
            nodes,
            shared,
            path,
            server,
            export,
            datastore,
            fingerprint,
            username,
            pool,
            vgname,
            thinpool,
            raw,
        } => {
            let mut typed: Vec<(&str, String)> = vec![("storage", storage), ("type", storage_type)];
            let push_opt =
                |t: &mut Vec<(&'static str, String)>, k: &'static str, v: Option<String>| {
                    if let Some(s) = v {
                        t.push((k, s));
                    }
                };
            push_opt(&mut typed, "content", content);
            push_opt(&mut typed, "nodes", nodes);
            if let Some(s) = shared {
                typed.push(("shared", if s { "1" } else { "0" }.to_string()));
            }
            push_opt(&mut typed, "path", path);
            push_opt(&mut typed, "server", server);
            push_opt(&mut typed, "export", export);
            push_opt(&mut typed, "datastore", datastore);
            push_opt(&mut typed, "fingerprint", fingerprint);
            push_opt(&mut typed, "username", username);
            push_opt(&mut typed, "pool", pool);
            push_opt(&mut typed, "vgname", vgname);
            push_opt(&mut typed, "thinpool", thinpool);
            let owned = build_params(typed, &raw)?;
            client.create_cluster_storage(&as_refs(&owned)).await?;
            Ok((serde_json::json!({"created": true}), 0))
        }
        StorageDefsCommand::Update {
            storage,
            content,
            nodes,
            disable,
            shared,
            fingerprint,
            delete,
            raw,
        } => {
            let mut typed: Vec<(&str, String)> = vec![];
            let push_opt =
                |t: &mut Vec<(&'static str, String)>, k: &'static str, v: Option<String>| {
                    if let Some(s) = v {
                        t.push((k, s));
                    }
                };
            push_opt(&mut typed, "content", content);
            push_opt(&mut typed, "nodes", nodes);
            if let Some(d) = disable {
                typed.push(("disable", if d { "1" } else { "0" }.to_string()));
            }
            if let Some(s) = shared {
                typed.push(("shared", if s { "1" } else { "0" }.to_string()));
            }
            push_opt(&mut typed, "fingerprint", fingerprint);
            push_opt(&mut typed, "delete", delete);
            if typed.is_empty() && raw.is_empty() {
                anyhow::bail!("update needs at least one field");
            }
            let owned = build_params(typed, &raw)?;
            client
                .update_cluster_storage(&storage, &as_refs(&owned))
                .await?;
            Ok((serde_json::json!({"updated": storage}), 0))
        }
        StorageDefsCommand::Delete { storage, yes } => {
            if !yes {
                anyhow::bail!("destructive — pass --yes to confirm");
            }
            client.delete_cluster_storage(&storage).await?;
            Ok((serde_json::json!({"deleted": storage}), 0))
        }
    }
}

/// ACME cluster-wide config dispatch. Account create/update/delete
/// return UPIDs because the CA round-trip is async.
#[allow(clippy::too_many_lines)]
pub async fn execute_acme(
    client: &Arc<crate::api::PxClient>,
    action: AcmeCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;

    fn build_params<'a>(
        typed: Vec<(&'a str, String)>,
        raw: &'a [String],
    ) -> Result<Vec<(&'a str, String)>> {
        let mut out = typed;
        for spec in raw {
            let (k, v) = spec
                .split_once('=')
                .ok_or_else(|| anyhow::anyhow!("--raw expects KEY=VAL, got {spec:?}"))?;
            out.retain(|(ek, _)| *ek != k);
            let key_static: &'static str = Box::leak(k.to_string().into_boxed_str());
            out.push((key_static, v.to_string()));
        }
        Ok(out)
    }
    fn as_refs<'a>(v: &'a [(&'a str, String)]) -> Vec<(&'a str, &'a str)> {
        v.iter().map(|(k, s)| (*k, s.as_str())).collect()
    }

    match action {
        AcmeCommand::Account(cmd) => match cmd {
            AcmeAccountCommand::List => {
                let accounts = client.list_acme_accounts().await?;
                Ok((serde_json::to_value(accounts)?, 0))
            }
            AcmeAccountCommand::Show { name } => {
                let a = client.get_acme_account(&name).await?;
                Ok((serde_json::to_value(a)?, 0))
            }
            AcmeAccountCommand::Create {
                name,
                contact,
                tos_url,
                directory,
                eab_kid,
                eab_hmac_key,
                raw,
            } => {
                let mut typed: Vec<(&str, String)> = vec![("name", name), ("contact", contact)];
                let push_opt =
                    |t: &mut Vec<(&'static str, String)>, k: &'static str, v: Option<String>| {
                        if let Some(s) = v {
                            t.push((k, s));
                        }
                    };
                push_opt(&mut typed, "tos_url", tos_url);
                push_opt(&mut typed, "directory", directory);
                // PVE accepts both `eab_kid` and `eab-kid`; we pick the
                // hyphen variant since that's what the docs show.
                push_opt(&mut typed, "eab-kid", eab_kid);
                push_opt(&mut typed, "eab-hmac-key", eab_hmac_key);
                let owned = build_params(typed, &raw)?;
                let upid = client.create_acme_account(&as_refs(&owned)).await?;
                Ok((serde_json::json!({"upid": upid}), 0))
            }
            AcmeAccountCommand::Update { name, contact, raw } => {
                let mut typed: Vec<(&str, String)> = vec![];
                if let Some(c) = contact {
                    typed.push(("contact", c));
                }
                if typed.is_empty() && raw.is_empty() {
                    anyhow::bail!("update needs at least one field");
                }
                let owned = build_params(typed, &raw)?;
                let upid = client.update_acme_account(&name, &as_refs(&owned)).await?;
                Ok((serde_json::json!({"upid": upid, "updated": name}), 0))
            }
            AcmeAccountCommand::Delete { name, yes } => {
                if !yes {
                    anyhow::bail!("destructive — pass --yes to confirm");
                }
                let upid = client.delete_acme_account(&name).await?;
                Ok((serde_json::json!({"upid": upid, "deleted": name}), 0))
            }
        },
        AcmeCommand::Plugin(cmd) => match cmd {
            AcmePluginCommand::List => {
                let plugins = client.list_acme_plugins().await?;
                Ok((serde_json::to_value(plugins)?, 0))
            }
            AcmePluginCommand::Show { plugin_id } => {
                let p = client.get_acme_plugin(&plugin_id).await?;
                Ok((serde_json::to_value(p)?, 0))
            }
            AcmePluginCommand::Create {
                plugin_id,
                plugin_type,
                api,
                data,
                validation_delay,
                raw,
            } => {
                let mut typed: Vec<(&str, String)> = vec![("id", plugin_id), ("type", plugin_type)];
                let push_opt =
                    |t: &mut Vec<(&'static str, String)>, k: &'static str, v: Option<String>| {
                        if let Some(s) = v {
                            t.push((k, s));
                        }
                    };
                push_opt(&mut typed, "api", api);
                push_opt(&mut typed, "data", data);
                if let Some(d) = validation_delay {
                    typed.push(("validation-delay", d.to_string()));
                }
                let owned = build_params(typed, &raw)?;
                client.create_acme_plugin(&as_refs(&owned)).await?;
                Ok((serde_json::json!({"created": true}), 0))
            }
            AcmePluginCommand::Update {
                plugin_id,
                api,
                data,
                validation_delay,
                disable,
                raw,
            } => {
                let mut typed: Vec<(&str, String)> = vec![];
                let push_opt =
                    |t: &mut Vec<(&'static str, String)>, k: &'static str, v: Option<String>| {
                        if let Some(s) = v {
                            t.push((k, s));
                        }
                    };
                push_opt(&mut typed, "api", api);
                push_opt(&mut typed, "data", data);
                if let Some(d) = validation_delay {
                    typed.push(("validation-delay", d.to_string()));
                }
                if let Some(d) = disable {
                    typed.push(("disable", if d { "1" } else { "0" }.to_string()));
                }
                if typed.is_empty() && raw.is_empty() {
                    anyhow::bail!("update needs at least one field");
                }
                let owned = build_params(typed, &raw)?;
                client
                    .update_acme_plugin(&plugin_id, &as_refs(&owned))
                    .await?;
                Ok((serde_json::json!({"updated": plugin_id}), 0))
            }
            AcmePluginCommand::Delete { plugin_id, yes } => {
                if !yes {
                    anyhow::bail!("destructive — pass --yes to confirm");
                }
                client.delete_acme_plugin(&plugin_id).await?;
                Ok((serde_json::json!({"deleted": plugin_id}), 0))
            }
        },
        AcmeCommand::Tos { directory } => {
            let tos = client.get_acme_tos(directory.as_deref()).await?;
            Ok((serde_json::json!({"tos_url": tos}), 0))
        }
        AcmeCommand::Directories => {
            let dirs = client.list_acme_directories().await?;
            Ok((serde_json::to_value(dirs)?, 0))
        }
        AcmeCommand::ChallengeSchema => {
            let schema = client.get_acme_challenge_schema().await?;
            Ok((schema, 0))
        }
    }
}

/// LXC template catalog dispatch. `download` returns a UPID — wrap
/// with `proxxx tasks --node X` to track completion.
pub async fn execute_aplinfo(
    client: &Arc<crate::api::PxClient>,
    action: AplinfoCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;
    match action {
        AplinfoCommand::List { node } => {
            let templates = client.list_node_aplinfo(&node).await?;
            Ok((
                serde_json::json!({"node": node, "count": templates.len(), "templates": templates}),
                0,
            ))
        }
        AplinfoCommand::Download {
            node,
            storage,
            template,
        } => {
            let upid = client
                .download_node_aplinfo(&node, &storage, &template)
                .await?;
            Ok((
                serde_json::json!({"upid": upid, "node": node, "storage": storage, "template": template}),
                0,
            ))
        }
    }
}

/// Feature #3 CLI dispatch. PBS lives in its own profile block; we don't
/// reuse the Proxmox API client. If `[profiles.X.pbs]` is missing, every
/// subcommand fails fast with a clear "configure PBS" message.
pub async fn execute_pbs(
    config: &crate::config::ProfileConfig,
    action: PbsCommand,
    cli_secret: Option<&str>,
) -> Result<(Value, i32)> {
    use crate::pbs::{PbsClient, PbsGateway};

    let pbs_cfg = config.pbs.clone().ok_or_else(|| {
        anyhow::anyhow!(
            "no [profiles.X.pbs] block configured — add url, user, token_id, token_secret(_file)"
        )
    })?;

    match action {
        PbsCommand::Ping => {
            let client = PbsClient::new(pbs_cfg, cli_secret).await?;
            let v = client.version().await?;
            Ok((
                serde_json::json!({
                    "ok": true,
                    "version": v.version,
                    "release": v.release,
                    "repo_id": v.repo_id,
                }),
                0,
            ))
        }
        PbsCommand::Datastores => {
            let client = PbsClient::new(pbs_cfg, cli_secret).await?;
            let stores = client.list_datastores().await?;
            Ok((serde_json::to_value(stores)?, 0))
        }
        PbsCommand::Snapshots {
            store,
            backup_type,
            backup_id,
        } => {
            let client = PbsClient::new(pbs_cfg, cli_secret).await?;
            let snaps = client
                .list_snapshots(&store, backup_type.as_deref(), backup_id.as_deref())
                .await?;
            Ok((serde_json::to_value(snaps)?, 0))
        }
        PbsCommand::Files {
            store,
            backup_type,
            backup_id,
            backup_time,
        } => {
            let client = PbsClient::new(pbs_cfg, cli_secret).await?;
            let files = client
                .list_snapshot_files(&store, &backup_type, &backup_id, backup_time)
                .await?;
            Ok((serde_json::to_value(files)?, 0))
        }
        PbsCommand::Restore {
            store,
            snapshot,
            archive,
            target,
            yes,
        } => {
            if !yes {
                anyhow::bail!("`pbs restore` writes to the local filesystem — re-run with --yes");
            }
            crate::pbs::restore::validate_target(&target)?;
            // Pre-flight: surface a clean error if the binary is missing
            // before we start streaming.
            if crate::pbs::detect_client_binary().is_none() {
                anyhow::bail!(
                    "proxmox-backup-client not found. Install the PBS client \
                     (apt install proxmox-backup-client on Debian/Ubuntu/PVE). \
                     Note: macOS / Windows clients aren't available upstream."
                );
            }
            let req = crate::pbs::RestoreRequest {
                snapshot: snapshot.clone(),
                archive: archive.clone(),
                target: target.clone(),
                store: store.clone(),
            };
            let mut tail: Vec<String> = Vec::new();
            let result = crate::pbs::run_restore(&pbs_cfg, cli_secret, req, |line| {
                tail.push(line.to_string());
                if tail.len() > 50 {
                    tail.drain(..tail.len() - 50);
                }
            })
            .await?;

            let exit = i32::from(result.exit_code != Some(0));
            Ok((
                serde_json::json!({
                    "store": store,
                    "snapshot": snapshot,
                    "archive": archive,
                    "target": target,
                    "exit_code": result.exit_code,
                    "last_lines": result.last_lines,
                    "status": if exit == 0 { "ok" } else { "error" },
                }),
                exit,
            ))
        }
    }
}

/// Feature #2 CLI dispatch.
pub async fn execute_iso(
    client: &Arc<crate::api::PxClient>,
    action: IsoCommand,
) -> Result<(Value, i32)> {
    use crate::api::ProxmoxGateway;
    use crate::app::iso_library;

    match action {
        IsoCommand::List => {
            let entries: Vec<Value> = iso_library::LIBRARY
                .iter()
                .map(|e| {
                    serde_json::json!({
                        "id": e.id,
                        "distro": e.distro,
                        "version": e.version,
                        "arch": e.arch,
                        "url": e.url,
                        // `checksum` is { "algo": "sha256"|"sha512", "digest": "..." }
                        // when pinned, or `null` when not (schema).
                        "checksum": e.checksum,
                        "content": e.content,
                        "size_mib": e.size_mib,
                        "notes": e.notes,
                    })
                })
                .collect();
            Ok((Value::Array(entries), 0))
        }
        IsoCommand::Download {
            id,
            url,
            filename,
            sha256,
            content,
            node,
            storage,
        } => {
            // Resolve either a library entry or a custom URL+filename+content.
            // We refuse ambiguous combinations loudly — pipelines should
            // know exactly what they asked for.
            //
            // `final_checksum` is `(algo, hex)` so curated entries that
            // ship SHA-512 (Debian) flow through unchanged.
            let (final_url, final_filename, final_checksum, final_content): (
                String,
                String,
                Option<(String, String)>,
                String,
            ) = match (id, url) {
                (Some(_), Some(_)) => {
                    anyhow::bail!("specify either --id or --url, not both");
                }
                (Some(entry_id), None) => {
                    let entry = iso_library::by_id(&entry_id)
                        .ok_or_else(|| anyhow::anyhow!("library id '{entry_id}' not found"))?;
                    // refuse-on-unpinned-checksum gate: curated entry must be pinned.
                    let checksum = entry.checksum.ok_or_else(|| {
                        anyhow::anyhow!(
                            "library entry '{entry_id}' has no pinned checksum. \
                             Use --url <X> --sha256 <Y> to download with caller-supplied checksum."
                        )
                    })?;
                    let (algo, hex) = checksum.proxmox_pair();
                    let derived_filename = entry
                        .url
                        .rsplit('/')
                        .next()
                        .unwrap_or("download.img")
                        .to_string();
                    (
                        entry.url.to_string(),
                        derived_filename,
                        Some((algo.to_string(), hex.to_string())),
                        entry.content.to_string(),
                    )
                }
                (None, Some(custom_url)) => {
                    let fname =
                        filename.ok_or_else(|| anyhow::anyhow!("--url requires --filename"))?;
                    let cnt = content.ok_or_else(|| {
                        anyhow::anyhow!("--url requires --content (iso|import|vztmpl)")
                    })?;
                    let cs = sha256.map(|h| ("sha256".to_string(), h));
                    (custom_url, fname, cs, cnt)
                }
                (None, None) => {
                    anyhow::bail!("specify --id <entry> or --url <custom-url>");
                }
            };

            let (algo, hex): (Option<&str>, Option<&str>) = match final_checksum.as_ref() {
                Some((a, h)) => (Some(a.as_str()), Some(h.as_str())),
                None => (None, None),
            };
            let upid = client
                .download_to_storage(
                    &node,
                    &storage,
                    &final_url,
                    &final_filename,
                    algo,
                    hex,
                    &final_content,
                )
                .await?;

            Ok((
                serde_json::json!({
                    "node": node,
                    "storage": storage,
                    "url": final_url,
                    "filename": final_filename,
                    "checksum": final_checksum,
                    "content": final_content,
                    "upid": upid,
                    "status": "queued"
                }),
                0,
            ))
        }
    }
}
