use serde::{Deserialize, Serialize};

use super::deserialize_bool_from_int;

/// One scheduled vzdump job. `GET|POST|PUT|DELETE /cluster/backup`.
///
/// All fields default-empty. PVE 7+ uses `schedule` (systemd-time
/// format like `mon..fri 02:00`); pre-7 used `starttime` + `dow` —
/// not modeled, those clusters won't see the field populated.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct BackupJob {
    /// Job id, autogenerated by PVE on POST (e.g. `backup-abc123`).
    /// Returned in list responses; required as URL segment for
    /// PUT/DELETE.
    pub id: String,

    /// systemd-time schedule expression. Example: `mon..fri 02:00`,
    /// `*-*-* 03:30`. The PVE web UI offers a builder; CLI users
    /// supply the literal string.
    pub schedule: String,

    /// Target storage id (e.g. `local`, `pbs-prod`).
    pub storage: String,

    /// `snapshot` (live, no downtime) | `stop` (full hard stop) |
    /// `suspend` (paused mid-backup). Default `snapshot`.
    pub mode: String,

    /// Whether the job is currently enabled (gets executed). PVE
    /// returns int 0/1; tolerant deserializer maps to bool.
    #[serde(deserialize_with = "deserialize_bool_from_int")]
    pub enabled: bool,

    /// `true` = backup ALL guests cluster-wide (or all on `node`
    /// when set). When false, `vmid` field carries the explicit list.
    #[serde(deserialize_with = "deserialize_bool_from_int", default)]
    pub all: bool,

    /// CSV of VMIDs when `all` is false. Empty when `all` is true.
    pub vmid: String,

    /// Restrict to a single node by name. Empty = cluster-wide.
    pub node: String,

    /// Notify destination — single email address or empty.
    pub mailto: String,

    /// `always` | `failure` (default). Empty in some versions.
    pub mailnotification: String,

    /// `none` | `lzo` | `gzip` | `zstd`. Default `zstd` on PVE 7+.
    pub compress: String,

    /// Free-text job comment (shown in the web UI). Empty by default.
    pub comment: String,

    /// vzdump notes template — `{{guestname}}`, `{{cluster}}`, etc.
    /// PVE serializes the field name with a hyphen.
    #[serde(rename = "notes-template")]
    pub notes_template: String,

    /// Retention policy DSL: `keep-last=3,keep-daily=7,keep-monthly=12`.
    /// PVE serializes with hyphen.
    #[serde(rename = "prune-backups")]
    pub prune_backups: String,

    /// Next scheduled run, Unix epoch seconds. 0 / absent when the
    /// scheduler hasn't computed it yet OR job is disabled.
    #[serde(rename = "next-run", default)]
    pub next_run: u64,
}
